### ISSUE TITLE
how could I train my own dataset use your repo?

### ISSUE THREAD

**Issue by gittigxuy** [yihui-he/softer-NMS#4]
compare with e2e_faster_rcnn_R-50-FPN_1x.yaml,your init.yaml adding [PROPOSAL_FILES],so,if I train my own dataset,it could be error,and it could train well when I train coco2014 dataset,so how could I train my own dataset?

I0928 10:56:50.334882 20043 context_gpu.cu:306] Total: 306 MB
INFO train.py: 192: Loading dataset: ('bdd100k_train_detection',)
Traceback (most recent call last):
  File "tools/train_net.py", line 132, in <module>
    main()
  File "tools/train_net.py", line 114, in main
    checkpoints = detectron.utils.train.train_model()
  File "/home/test/code/softer-NMS/detectron/utils/train.py", line 58, in train_model
    setup_model_for_training(model, weights_file, output_dir)
  File "/home/test/code/softer-NMS/detectron/utils/train.py", line 170, in setup_model_for_training
    add_model_training_inputs(model)
  File "/home/test/code/softer-NMS/detectron/utils/train.py", line 194, in add_model_training_inputs
    cfg.TRAIN.DATASETS, cfg.TRAIN.PROPOSAL_FILES
  File "/home/test/code/softer-NMS/detectron/datasets/roidb.py", line 60, in combined_roidb_for_training
    assert len(dataset_names) == len(proposal_files)
AssertionError

**Comment by yihui-he** [comment]
I think the other issue answers your question. #2

**Comment by yihui-he** [comment]
If you want to integrate softer-NMS into your own code, you can find all modifications to `detectron/` at lines with flags: `XYXY, PRED_STD, STD_NMS`.

**Comment by gittigxuy** [comment]
我看报错信息主要就是RPN Proposal的模型仅仅对于coco数据集进行了适配，而没有对于我自己的数据集进行适配，这种情况如何解决呢？

**Comment by yihui-he** [comment]
你如果用end2end，就按照我的config改一个end2end的config就行了。我train的是fast rcnn
需要proposal。

**Comment by gittigxuy** [comment]
ok,谢谢了，试试看，有问题再请教，我用的确实是end2end

**Comment by yihui-he** [comment]
this repo is deprecated. Please use our new repo which also improved performance: https://github.com/yihui-he/KL-Loss
